### ISSUE TITLE
Permission to modify code?

### ISSUE THREAD

**Issue by CodeOptimist** [kevlou/RimWorld_WhileYoureUp#3]
(First of all, this mod is brilliant, thank you.)
Since your source code isn't included in this MIT-licensed repository I'm unsure if you meant to license it as well. As it stands essentially only the description and language strings are, which allows for translations and use but no legal code modifications. C# is of course easily decompiled but I want to make sure I have your permission to create derivatives before using that. ;) Thanks!

**Comment by hopeseekr** [comment]
There's no C# code in this repository at all. Just a DLL. Very closed source, very uncool.

**Comment by CodeOptimist** [comment]
Issue closed as I ended up [branching RimWorld 1.0's implementation](https://github.com/CodeOptimist/rimworld-jobs-of-opportunity) [of opportunistic hauling](https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453) instead of this one. No doubt 1.0's implementation was likely inspired by this mod though. ♥
